CSE190Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
]

main/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home_view, name='home-view'),
    path('import', views.import_excel, name='import-view'),
    path('submit', views.submit, name='submit-view'),
]

category/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.TextField(max_length=255, unique=True)

    def __str__(self):
        return self.name

course/models.py
from django.db import models

# Create your models here.
class Courses(models.Model):
    name = models.TextField(max_length=16, unique=True)
    title = models.TextField(max_length=256)
    description = models.TextField(max_length=1024)
    units = models.PositiveIntegerField()
    difficulty = models.PositiveIntegerField()
    categories = models.ManyToManyField("category.Category")

    def __str__(self):
        return self.name

    def underscore(self):
        return self.name.replace(' ', '_')

main/models.py
from django.db import models

# Create your models here.

course/views.py
from django.shortcuts import render

# Create your views here.

main/views.py
from django.shortcuts import render
from django.http import HttpResponse
import openpyxl
import os
from course.models import Courses
from category.models import Category

# Create your views here.
def home_view(request):
    return render(request, 'main/home.html')

def submit(request):
    difficulties = request.GET.get("selected_difficulties").split(',')
    units = request.GET.get("selected_units").split(',')
    string_categories = request.GET.get("total_categories").split(',')
    categories = []
    for category in string_categories:
        item = Category.objects.get(name=category)
        categories.append(item)
    courses = Courses.objects.filter(difficulty__in=difficulties, units__in=units, categories__in=categories).distinct()
    context = {
        "difficulties": difficulties,
        "units": units,
        "categories": string_categories,
        "courses": courses,
    }
    return render(request, 'main/result.html', context)

def import_excel(request):
    path = os.path.join(os.path.expanduser('~'), 'Downloads', 'Undergraduate CSE Electives.xlsx')
    wb = openpyxl.load_workbook(filename=path, data_only=True)['Sheet1']
    rows = []
    for i in range(1, wb.max_row+1):
        row = [cell.value for cell in wb[i][0:7+1]] # sheet[n] gives nth row (list of cells)
        rows.append(row)
    for index,row in enumerate(rows):
        if index > 0:
            course = Courses.objects.get(name=row[0])
            # course_categories = row[6].split(",")
            # course_categories = [x.strip() for x in course_categories]
            # for category in course_categories:
            #     category = Category.objects.get(name=category)
            #     course.categories.add(category)
    return HttpResponse(200)

main/templates/main/home.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    <div class="center-div">
        <h1><b>Welcome to the UCSD Course Recommender!</b></h1>
        <br><br>
        <!-- Page One: Selecting Completed Courses-->
        <div style="height: 35rem;">
            <!-- Page One: Selecting Ideal Difficulty-->
            <div class="center-div page" id="page-one">
                <h4>Step 1. Select your preferred course difficulty (defined by hours per week)</h4>
                <br><br>
                <div style="display: flex;">
                    <div style="flex: 1;">
                        <h3>Easy</h3>
                        <img src={% static '1.png'%} class="unselected" name="1" style="max-width: 25rem; margin-bottom: 0.75rem;"></img>
                        <br> 
                        <i>&lt;6 hours per week</i>
                    </div>
                    <div style="flex: 1;">
                        <h3>Medium</h3>
                        <img src={% static '2.png'%} class="unselected" name="2" style="max-width: 25rem; margin-bottom: 0.75rem;"></img>
                        <br>      
                        <i>6-9 hours per week</i>
                    </div>
                    <div style="flex: 1;">
                        <h3>Hard</h3>
                        <img src={% static '3.png'%} class="unselected" name="3" style="max-width: 25rem; margin-bottom: 0.75rem;"></img>
                        <br>               
                        <i>9-12 hours per week</i>
                    </div>
                    <div style="flex: 1;">
                        <h3>Death</h3>
                        <img src={% static '4.png'%} class="unselected" name="4" style="max-width: 25rem; margin-bottom: 0.75rem;"></img>
                        <br>               
                        <i>&gt;13 hours per week</i>
                    </div>
                </div>
                <br>
            </div>
            <!-- Page Two: Selecting Desired Units-->
            <div class="center-div invisible page" style="max-width: 40rem;" id="page-two">
                <h4>Step 2. Select your ideal number of units per course</h4>
                <br><br><br>
                <div style="display: flex;">
                    <div style="flex: 1;">
                        <h3>Two Units</h3>
                        <btn class="btn btn-primary unselected unit-button" name="2">2</btn>
                    </div>
                    <div style="flex: 1">
                    </div>
                    <div style="flex: 1;">
                        <h3>Four Units</h3>
                        <btn class="btn btn-primary unselected unit-button" name="4">4</btn>
                    </div>
                </div>
                <br>
            </div>
            <!-- Page Three: Selecting Topics of Interest-->
            <div class="center-div invisible page" style="max-width: 40rem;" id="page-three">
                <h4 style="margin-bottom: 0.75rem; width: 100%;">Step 3. Select categories that you're interested in</h4>
                <br><br>
                <div style="display: flex">
                    <div style="flex: 1; font-size: 1.25rem; text-align: left;">
                        <input type="checkbox" id="software_engineering" value="Software Engineering">
                        <label for="software_engineering">Software Engineering</label><br>
                        <input type="checkbox" id="web_development" value="Web Development">
                        <label for="web_development">Web Development</label><br>
                        <input type="checkbox" id="machine_learning" value="Machine Learning">
                        <label for="machine_learning">Machine Learning</label><br>
                        <input type="checkbox" id="data_science" value="Data Science">
                        <label for="data_science">Data Science</label><br>
                        <input type="checkbox" id="databases" value="Databases">
                        <label for="databases">Databases</label><br>
                        <input type="checkbox" id="math" value="Math">
                        <label for="math">Math</label><br>
                        <input type="checkbox" id="architecture" value="Architecture">
                        <label for="architecture">Architecture</label><br>
                        <input type="checkbox" id="theory" value="Theory">
                        <label for="theory">Theory</label><br>
                    </div>
                    <div style="text-align: right;">
                    <div style="flex: 1; font-size: 1.25rem; text-align: left;">
                        <input type="checkbox" id="computer_vision" value="Computer Vision">
                        <label for="computer_vision">Computer Vision</label><br>
                        <input type="checkbox" id="design_interaction" value="Design & Interaction">
                        <label for="design_interaction">Design & Interaction</label><br>
                        <input type="checkbox" id="research" value="Research">
                        <label for="research">Research</label><br>
                        <input type="checkbox" id="group_project" value="Group Project">
                        <label for="group_project">Group Project</label><br>
                        <input type="checkbox" id="biology" value="Biology">
                        <label for="biology">Biology</label><br>
                        <input type="checkbox" id="education_teaching" value="Education & Teaching">
                        <label for="education_teaching">Education & Teaching</label><br>
                        <input type="checkbox" id="management" value="Management">
                        <label for="management">Management</label><br>
                    </div>
                    </div>
                </div>
            </div>
        </div>
        <form action="/submit" id="submit_form" method="GET">
            <input name="selected_difficulties" type="hidden">
            <input name="selected_units" type="hidden">
            <input name="total_categories" type="hidden">
            <button class="btn btn-primary" id="previous-button" style="margin-right: 2rem; width: 10rem;" type="button" disabled><h4>Previous</h4></button>
            <button class="btn btn-primary" id="next-button" style="margin-left: 2rem; width: 10rem;" type="button" disabled><h4>Next</h4></button>
        </form>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        $(document).ready(function(){
            // Page 1 JS
            var selected_difficulties = [];
            $("img").on('click', function(){
                if ($(this).attr("id") != "go_bears"){
                    let difficulty = $(this).attr("name")
                    if ($(this).hasClass("unselected")){
                        $(this).removeClass("unselected");
                        $(this).addClass("selected");
                        selected_difficulties.push(difficulty);
                        $("#next-button").prop("disabled",false);
                    }
                    else {
                        $(this).removeClass("selected");
                        $(this).addClass("unselected");
                        let index = selected_difficulties.indexOf(difficulty);
                        if (index > -1) {
                            selected_difficulties.splice(index, 1);
                        }
                        if (selected_difficulties.length == 0){
                            $("#next-button").prop("disabled",true);
                        }
                    }
                    $("#submit_form input[name=selected_difficulties]").val(selected_difficulties);
                }
            });
            var selected_units = [];
            // Page 2 JS
            $("btn").on('click', function(){
                let unit = $(this).attr("name")
                if ($(this).hasClass("unselected")){
                    $(this).removeClass("unselected");
                    $(this).addClass("selected");
                    selected_units.push(unit);
                    $("#next-button").prop("disabled",false);
                }
                else {
                    $(this).removeClass("selected");
                    $(this).addClass("unselected");
                    let index = selected_units.indexOf(unit);
                    if (index > -1) {
                        selected_units.splice(index, 1);
                    }
                    if (selected_units.length == 0){
                        $("#next-button").prop("disabled",true);
                    }
                }
                $("#submit_form input[name=selected_units]").val(selected_units);
            });

            // Page 3 JS
            var total_categories = [];
            $("input").on("click", function(event){
                let category = $(this).attr("value");
                if (!total_categories.includes(category)){
                    total_categories.push(category);
                    $("#next-button").prop("disabled",false);
                }
                else {
                    let index = total_categories.indexOf(category);
                    if (index > -1) {
                        total_categories.splice(index, 1);
                    }
                }
                if (total_categories.length == 0){
                    $("#next-button").prop("disabled",true);
                }
                $("#submit_form input[name=total_categories]").val(total_categories);
            });

            // Page navigation
            var current_page = 1;
            var time = 250;
            $("#next-button").on("click", function(){
                if($(this).hasClass("processing"))
                    return;                
                $(this).addClass("processing");
                $("#previous-button").prop('disabled', false);
                if (current_page == 1){ 
                    var fade_out_page_id = "page-one";
                    var fade_in_page_id = "page-two";
                    if (selected_units.length == 0)
                        $("#next-button").prop("disabled",true);
                }
                else if (current_page == 2){
                    var fade_out_page_id = "page-two";
                    var fade_in_page_id = "page-three";
                    if (total_categories.length == 0)
                        $("#next-button").prop("disabled",true);
                    $("#next-button").html("<h4>Finish</h4>");
                    $("#next-button").removeAttr("type").attr("type", "submit");
                    event.preventDefault();
                }
                $("#" + fade_out_page_id).fadeOut(time);                
                setTimeout(function() {
                    $("#" + fade_in_page_id).hide();
                    $("#" + fade_in_page_id).removeClass('invisible');
                    $("#" + fade_in_page_id).fadeIn(time);
                    $('#next-button').removeClass("processing");
                }, time);
                current_page++;
            });
            $("#previous-button").on("click", function(){
                if($(this).hasClass("processing"))
                    return;                
                $(this).addClass("processing");
                if (current_page == 2){ 
                    var fade_out_page_id = "page-two";
                    var fade_in_page_id = "page-one";
                    $("#previous-button").prop('disabled', true);
                    $("#next-button").prop("disabled",false);
                }
                else if (current_page == 3){ 
                    var fade_out_page_id = "page-three";
                    var fade_in_page_id = "page-two";
                    $("#next-button").html("<h4>Next</h4>");
                    $("#next-button").removeAttr("type").attr("type", "button");
                }
                $("#" + fade_out_page_id).fadeOut(time);                
                setTimeout(function() {
                    $("#" + fade_in_page_id).hide();
                    $("#" + fade_in_page_id).removeClass('invisible');
                    $("#" + fade_in_page_id).fadeIn(time);
                    $('#previous-button').removeClass("processing");
                }, time);
                current_page--;
            });
        });        
    </script>
{% endblock %}

main/templates/main/result.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Results
{% endblock %}

{% block content %}
    <div class="center-div" style="width: 60rem">
        <h2>Based on your selection, we recommend these courses</h2>
        <br>
        <div style="text-align: left">
            <b>Difficulty: 
                {% for difficulty in difficulties reversed%}
                    {% if forloop.last%}
                        {{difficulty}}
                    {% else %}
                        {{difficulty}}, 
                    {% endif %}
                {% endfor %}
            </b><br>
            <b>Units: 
                {% for unit in units %}
                    {% if forloop.last%}
                        {{unit}}
                    {% else %}
                        {{unit}}, 
                    {% endif %}
                {% endfor %}
            </b><br>
            <b>Categories: 
                {% for category in categories %}
                    {% if forloop.last%}
                        {{category}}
                    {% else %}
                        {{category}}, 
                    {% endif %}
                {% endfor %}        
            </b><br><br>
            {% if courses %}
                {% for course in courses %}
                    <div class="ui accordion" style="margin-bottom: 0.5rem;" >                  
                        <div class="title" id="{{course.underscore}}">
                            <i class="dropdown icon"></i>
                            <b style="font-size: 1.25rem;">{{course.name}}&nbsp;&nbsp;{{course.title}}&nbsp;&nbsp;({{course.units}})</b>
                        </div>
                        <div class="content" style="margin-left: 2.5rem;">
                            <div class="transition hidden" style="text-align: left;">
                                <span><b>Description</b></span>
                                <p>{{course.description}}</p>
                                <p><b>Categories: </b>
                                {% for category in course.categories.all %}
                                    {% if forloop.last%}
                                        {{category}}
                                    {% else %}
                                        {{category}}, 
                                    {% endif %}
                                {% endfor %}  
                                </p>
                                <p><b>Workload: </b>{{course.difficulty}}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <h2 style="text-align: center; margin-top: 10rem;"><i>No classes meet your criteria. Try a broader search!</i></h2>
            {% endif %}
        </div>
        <br>
        <a href={% url 'main:home-view' %}><button class="btn btn-primary" style="font-size: 1.25rem;">Search Again</button></a>
    </div>
    <br>
{% endblock %}

{% block scripts %}
    <script>
        var accordion = {
            accordion: $('.ui.accordion'),
            duration: 200,
        };
        $('.ui.accordion').accordion(accordion);
        $(".title").on("click", function(){
            let id = $(this).attr('id');
            setTimeout(function(){                
                $('html, body').animate({
                    scrollTop: $("#" + id).offset().top-60
                }, 200);
            }, 50)
            
        })
    </script>
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

    <!-- jQuery UI-->
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>

    <!-- Fomantic UI -->
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/fomantic-ui@2.8.8/dist/semantic.min.css">
    <script src="https://cdn.jsdelivr.net/npm/fomantic-ui@2.8.8/dist/semantic.min.js"></script>


    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Cropper -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.12/cropper.js" integrity="sha512-ZK6m9vADamSl5fxBPtXw6ho6A4TuX89HUbcfvxa2v2NYNT/7l8yFGJ3JlXyMN4hlNbz0il4k6DvqbIW5CCwqkw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.12/cropper.css" integrity="sha512-+VDbDxc9zesADd49pfvz7CgsOl2xREI/7gnzcdyA9XjuTxLXrdpuz21VVIqc5HPfZji2CypSbxx1lgD7BgBK5g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cropper/1.0.1/jquery-cropper.js" integrity="sha512-7H4tikIFoyAdYD31w/uNYvvAUL6gyunWXLwTQ7ZXkyjD+brw+PfJpLxFkANnbkKnSJzU89YpnF3fJKbpvV+QYg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cropper/1.0.1/jquery-cropper.min.js" integrity="sha512-V8cSoC5qfk40d43a+VhrTEPf8G9dfWlEJgvLSiq2T2BmgGRmZzB8dGe7XAABQrWj3sEfrR5xjYICTY4eJr76QQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    
    <!-- Custom CSS & JS -->
    <link rel="stylesheet" href={% static 'style.css' %}>
    <title>UCSD Course Recommender | {% block title %} {% endblock title %}</title>
  </head>  
  
  <body>
    <!-- Navbar -->
    {% include 'navbar.html' %}
    <br><br><br><br><br>
    <div class="main-content">
      {% block content %}
      {% endblock %}
    </div>
    <div class="footer">
      <a href="https://www.berkeley.edu/" style="text-decoration: none; display: inline-block; width: 15rem;">
      <div style="display: flex; align-items: center; margin: 1.5rem;">
        <img src="{% static 'go_bears.png'%}" style="width: 3.5rem;" id="go_bears"></img>
        <p style="color: white; font-size: 1.25rem; margin-left: 0.75rem;"><i>Go Bears</i></p>
      </div>
      </a>
    </div>
    <script>
        const token = '{{ csrf_token }}'
    </script>
  </body>
  <script>
    $(".navbar-container .bars.icon").on("click", function(){
      $(".ui.sidebar").sidebar('toggle');
    });
  </script>
  {% block scripts %}
  {% endblock %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
</html>

templates/navbar.html
{% load static %}

<div class="ui fixed inverted menu">
    <a href="{% url 'main:home-view' %}" class="item">
        <h3><b>UCSD Course Finder</b></h3>&nbsp;&nbsp;
    </a>
</div>